# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

AllCops:
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
